### ISSUE TITLE
Any way to import it as a static resource

### ISSUE THREAD

**Issue by devsawgrad** [salesforce/kagekiri#86]
I am looking to use this to implement tab trapping in a modal inside a LWC. is there a way to import it as a static resource?

**Comment by nolanlawson** [comment]
Thanks for opening this issue. In the future, I would recommend posting this issue on [Salesforce StackExchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) or opening a [Salesforce case](https://help.salesforce.com/s/).

In general, kagekiri is most useful as a testing tool. I would generally not recommend using it in production, due to its large bundle size and potential issues with access to element `shadowRoot`s being blocked by Locker/LightningWebSecurity. That said, you can use a tool like [Rollup](https://rollupjs.org/) to build it as a bundled JS file.

For tab-trapping in a modal, does something like [lightning-modal](https://developer.salesforce.com/docs/component-library/bundle/lightning-modal/documentation) not solve this issue? If not, please open the StackExchange post or case as mentioned above. Thank you!
